name: Run Unit Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: run tests
      run: go test -v -coverprofile=cover.out -covermode=count ./...
    - name: generate coverage file
      run: go tool cover -html=cover.out -o cover.html
    - name: upload coverage
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: cover.html 
